### ISSUE TITLE
jqapi.com timing out

### ISSUE THREAD

**Issue by an-dev** [mustardamus/jqapi#17]
`http://jqapi.com/` doesn't seem to be accessible anymore.

```
~/$ ping jqapi.com
PING jqapi.com (205.186.152.154) 56(84) bytes of data.
^C
--- jqapi.com ping statistics ---
42 packets transmitted, 0 received, 100% packet loss, time 41962ms

[1]+  Done
```

I appreciate the project hasn't been updated/maintained in a while, so it would be nice to know if you guys are still hosting it or not

**Comment by mustardamus** [comment]
Hi Andy! Thanks for letting me know. MediaTemple, where jQAPI is hosted, is upgrading to a new infrastructure, thus the downtime. The new server should be ready any day now, then I update the DNS and it's hopefully back online.

I'll let you know via this issue. Cheers.

**Comment by diegonella** [comment]
i need jqapi online, is the blood for my code

**Comment by mustardamus** [comment]
Hi @an-dev and @diegonella ,

http://jqapi.com is back online. Also, inspired by your requests, I've started jQAPI3 which will be powered by Astro and is all JS.

Best,
Basti

**Comment by an-dev** [comment]
@mustardamus Just a heads up, the link appears to be down again as of this post

**Comment by mustardamus** [comment]
Unfortunately the server migration is still not done and there are very spare updates from MediaTemple (Namecheap owns them now). I restarted the old server, and it seems to be working again.  Hope it stays up and/or the migration is finished soon, but I'll check it every now and then. @an-dev

**Comment by an-dev** [comment]
@mustardamus Legend. Let us know if we can help in any way to keep the project running.

**Comment by mustardamus** [comment]
Quick update: Because the server at MediaTemple is shutting down, and I can't reach their support, I moved jQAPI temporarily (?) to another server. It should be back online for good when the DNS changes kick in.

In other news, I make progress with the new jQAPI: https://github.com/jqapi/jqapi/tree/next

**Comment by mustardamus** [comment]
@an-dev @diegonella Heya! I've released the new jQAPI! Have a look: https://jqapi.com All future development will happen here: https://github.com/jqapi/jqapi

Thanks, and see you there :)
